version: '3.9'

services:
  demo-http:
    image: ${DOCKER_REGISTRY-}atops-demo-http
    deploy:
      labels:
        com.docker.compose.project.config_files: "Dotnet Minimal API Demo"
    build:
      context: .
      dockerfile: DemoHttp/Dockerfile