name: Push to Docker Hub

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: 🔨 Nerdbank.GitVersioning
        uses: dotnet/nbgv@v0.4.0
        with:
          setAllVars: true

      - name: 👷 Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🚀 Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: si618/argocd-demo-app:latest,si618/argocd-demo-app:${{ env.NBGV_SimpleVersion }}
